FROM node:18-alpine

WORKDIR /app

# Copia package.json e installa dipendenze
COPY package*.json ./
RUN npm install

# Esponi la porta di sviluppo
EXPOSE 5173

# Comando di default (può essere sovrascritto da docker-compose)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
