# Plesk deployment configuration
# Questo file viene letto automaticamente da Plesk quando fai un deploy via Git

# Script che viene eseguito dopo ogni pull da Git
post_deploy:
  - echo "🚀 Avvio deployment automatico..."
  
  # Backend: installa dipendenze Python
  - echo "📦 Installazione dipendenze backend..."
  - cd backend && pip3 install -r requirements.txt --user
  
  # Frontend: installa dipendenze e build
  - echo "🎨 Build frontend..."
  - cd ../frontend
  - npm install
  - npm run build
  
  # Crea cartella uploads se non esiste
  - echo "📁 Preparazione cartelle..."
  - mkdir -p ../uploads
  - chmod 777 ../uploads
  
  # Crea file .env se non esiste (da configurare manualmente dopo)
  - echo "⚙️ Configurazione ambiente..."
  - cd ../backend
  - if [ ! -f .env ]; then cp .env.example .env; echo "⚠️ IMPORTANTE: Configura backend/.env con le credenziali del database!"; fi
  
  # Inizializza database (solo se .env è configurato)
  - echo "🗄️ Inizializzazione database..."
  - python3 init_data.py || echo "⚠️ Errore init database - configura prima .env!"
  
  # Avvia/Riavvia backend (se già in esecuzione lo riavvia)
  - echo "🔄 Avvio backend..."
  - pkill -f "uvicorn main:app" || true
  - nohup python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 > ../backend.log 2>&1 &
  - echo "Backend avviato su porta 8000 (log: backend.log)"
  
  - echo "✅ Deployment completato!"
  - echo "📍 Frontend disponibile in: frontend/dist/"
  - echo "🔧 Configura Document Root su: frontend/dist"
  - echo "🔧 Configura Nginx proxy per /api → http://localhost:8000"

