version: '3.8'

services:
  # MariaDB Database
  db:
    image: mariadb:10.11
    container_name: bennati_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: bennati_checklist
      MYSQL_USER: bennati
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "bennati", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.portainer
    container_name: bennati_backend
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://bennati:${DB_PASSWORD}@db:3306/bennati_checklist
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      UPLOAD_DIR: ./uploads
      CORS_ORIGINS: ${CORS_ORIGINS}
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  # Frontend React
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.portainer
    container_name: bennati_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mariadb_data:
  backend_uploads:
