version: '3.8'

services:
  # Backend FastAPI
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.portainer
    container_name: bennati_backend
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://bennati:${DB_PASSWORD}@host.docker.internal:3306/bennati_checklist
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      UPLOAD_DIR: ./uploads
      CORS_ORIGINS: ${CORS_ORIGINS}
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    volumes:
      - backend_uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Frontend React
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.portainer
    container_name: bennati_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend_uploads:
