version: '3.8'

services:
  # Backend FastAPI
  backend:
    build: ./backend
    container_name: simple_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=your-secret-key-change-this-in-production
    volumes:
      - ./backend/checklist.db:/app/checklist.db
    command: >
      sh -c "python init_data.py && uvicorn main:app --host 0.0.0.0 --port 8000"

  # Frontend Node.js
  frontend:
    build: ./frontend
    container_name: simple_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
